# Generated by Django 3.2.5 on 2021-08-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Categories')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100)),
                ('author', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('pdf', models.FileField(upload_to='pdf')),
                ('crime_books', models.BooleanField(default=False)),
                ('Biography_books', models.BooleanField(default=False)),
                ('selfHelp_books', models.BooleanField(default=False)),
                ('programming_books', models.BooleanField(default=False)),
                ('genre', models.ManyToManyField(related_name='books', to='bookapp.Category')),
            ],
        ),
    ]
